# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  default

steps:
- task: SaveCache@0
  inputs:
    key: 'MultiEmptyFilesCache'
    path: 'EmptyFiles/'

- task: RestoreCache@0
  inputs:
    key: MultiEmptyFilesCache
    path: '$(System.ArtifactsDirectory)'

- task: SaveCache@0
  inputs:
    key: 'MultiNonEmptyFilesCache'
    path: 'NonEmptyFiles/'

- task: RestoreCache@0
  inputs:
    key: MultiNonEmptyFilesCache
    path: '$(System.ArtifactsDirectory)'

- task: SaveCache@0
  inputs:
    key: 'AdditionalSingleFileCache'
    path: 'bar.cs'

- task: RestoreCache@0
  inputs:
    key: AdditionalSingleFileCache
    path: '$(System.ArtifactsDirectory)'

- task: RestoreCache@0
  inputs:
    path: '$(System.ArtifactsDirectory)'
