# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: v-nicro

steps:
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'SingleFileDrop'
    targetPath: 'foo.cs'

- task: DownloadPipelineArtifact@1
  inputs:
    artifactName: SingleFileDrop
    downloadPath: '$(System.ArtifactsDirectory)'
